export const LIST_COURSES_REQUEST = 'LIST_COURSES_REQUEST';
export const LIST_COURSES_SUCCESS = 'LIST_COURSES_SUCCESS';
export const LIST_COURSES_FAIL = 'LIST_COURSES_FAIL';

export const SINGLE_COURSE_REQUEST = 'SINGLE_COURSE_REQUEST';
export const SINGLE_COURSE_SUCCESS = 'SINGLE_COURSE_SUCCESS';
export const SINGLE_COURSE_FAIL = 'SINGLE_COURSE_FAIL';